de-coupled image name from container name. This allowed a whole lot of commands like inspect, top and logs to be possible

diff --git a/totally b/totally
--- a/totally
+++ b/totally
@@ -32,7 +32,7 @@ function usage() {
 	Main commands:
 
 	.	init	Initialise a new project named after the current directory
-	.	deploy	Builds and restarts your app - this is your fast feed back loop
+	.	run 	Builds a Docker image for your app, and runs it.
 
 	Troubleshooting commands:
 
@@ -57,7 +57,11 @@ function cmd_init() {
 	[ -f .totally ] && die "This directory has already been initialised. 'cat .totally' to see your project."
 
 	local name=$(basename $PWD)
-	echo NAME=\"$name\" > .totally
+	cat > .totally <<-HERE
+		NAME="$name"
+		IMAGE="\$NAME:latest"
+		CONTAINER="\$USER-\$NAME"
+	HERE
 	echo Initialised new Totally project called $name
 }
 
@@ -77,12 +81,16 @@ function configuration_walk() {
 		LOCAL_ROOT=$PWD # The last recursed $PWD should be the local project root
 }
 
-function validate_configuration() {
+function validate() {
 	[ -z "$DOCKER_SSH_HOST" ] && error "Missing docker host name env DOCKER_SSH_HOST"
-	[ -z "$NAME" ] && error "Missing project name env NAME. Are you in a project? Have you run a totally init?" 
-	
+	[ -z "$NAME" ] && error "Missing project name env: NAME" 
+	[ -z "$IMAGE" ] && error "Missing Docker image env: IMAGE" 
+	[ -z "$CONTAINER" ] && error "Missing Docker container name env: CONTAINER" 
+
+	[ ! -f "$LOCAL_ROOT/Dockerfile" ] && error "Missing a Dockerfile at $LOCAL_ROOT. I wouldn't know how to run your app without it."
+
 	(( ERRORS > 0 )) && 
-		die "Add missing envs to a .totally file either in your home directory, or project directories."
+		die "Add missing envs to a .totally file either in your home directory, or project directory."
 }
 
 function configure() {
@@ -94,7 +102,7 @@ function configure() {
 
 	if [ -z "$REMOTE_ROOT" ]; then REMOTE_ROOT=totally-build; fi
 
-	validate_configuration
+	validate
 }
 
 function sync_up() {
@@ -103,35 +111,53 @@ function sync_up() {
 }
 
 function build_image() {
-	ssh $DOCKER_SSH_HOST "cd $REMOTE_ROOT/$NAME && echo building $NAME in \$HOSTNAME:\$PWD; docker build -t $NAME ."
+	ssh $DOCKER_SSH_HOST "cd $REMOTE_ROOT/$NAME && echo building $IMAGE in \$HOSTNAME:\$PWD; docker build -t $IMAGE ."
 }
 
 function restart_container() {
 	ssh $DOCKER_SSH_HOST <<-HERE
-	echo "restarting $NAME"
-	docker stop "$NAME"
-	docker rm "$NAME"
-	docker run --name "$NAME" -d $NAME
+	echo "restarting $CONTAINER"	
+	set -x
+	docker stop "$CONTAINER"
+	docker rm "$CONTAINER"
+	docker run --name "$CONTAINER" -d $IMAGE
+	docker logs "$CONTAINER"
 	HERE
 }
 
 function cmd_build() {
 	configure
-	echo building Docker image called $NAME on $DOCKER_SSH_HOST
+	echo building Docker image called $IMAGE on $DOCKER_SSH_HOST
 
 	sync_up
 	build_image
 }
 
-function cmd_deploy() {
+function cmd_run() {
 	configure
-	echo deploying $NAME \($LOCAL_ROOT\) to $DOCKER_SSH_HOST:$REMOTE_ROOT
+	echo running $NAME \($LOCAL_ROOT\) to $DOCKER_SSH_HOST:$REMOTE_ROOT
 	
 	sync_up
 	build_image
 	restart_container
 }
 
+function cmd_logs() {
+	configure
+	ssh $DOCKER_SSH_HOST "echo Tailing logs for $CONTAINER. Hit ^C to stop; docker logs --follow $CONTAINER"	
+}
+
+function cmd_inspect() { 
+	configure
+	ssh $DOCKER_SSH_HOST "docker inspect $CONTAINER"
+}
+
+function cmd_top() { 
+	configure
+	ssh $DOCKER_SSH_HOST "docker top $CONTAINER"
+}
+
+function cmd_man() { :; }
 
 function command_loop() {
 	if [ -z "$1" ]; then
@@ -144,7 +170,7 @@ function command_loop() {
 		shift
 
 		if [ $( type -t cmd_$CMD ) = "function" ]; then
-			cmd_$CMD
+			cmd_$CMD || die "Oops! $CMD exited with $?"
 		else
 			error Sorry, no such command $CMD
 			usage
